services:
  postgres:
    image: postgres:15-alpine
    container_name: pokemon_ev_db
    environment:
      POSTGRES_DB: pokemon_ev
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: pikachu123
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trainer -d pokemon_ev"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-init:
    build: ./db/init
    container_name: python_init_script
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pokemon_ev
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: pikachu123
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./db/scrapingNew:/app/scrapingNew
    command: >
      sh -c "
        echo 'Esperando que Postgres est√© listo...' &&
        python3 ./02_load_data.py &&
        python3 ./04_load_geography.py &&
        python3 ./03_verify_data.py
      "
  backend:
    build: ./backend
    container_name: pokemon_backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: pokemon_ev
      POSTGRES_USER: trainer
      POSTGRES_PASSWORD: pikachu123
      POSTGRES_PORT: 5432
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - postgres
      - backend